name: Daily Commit

on:
  schedule:
    - cron: '30 3 * * *'  # Runs daily at 9:00 AM IST (03:30 UTC)
  workflow_dispatch:  # Optional manual trigger

jobs:
  daily-commit-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Daily Commit by 24f3004689@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date -u)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Daily update: $(date -u)"
          git push
